# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_Pendaftaran_Akun.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(882, 565)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 881, 561))
        self.frame.setStyleSheet("background-color: rgb(0, 85, 127)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(640, 520, 211, 31))
        self.label_3.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(780, 10, 91, 61))
        self.label_5.setStyleSheet("image: url(:/newPrefix/D:/Draw Io/drive-download-20240321T065022Z-001/ICON.png)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(660, 10, 91, 61))
        self.label_6.setStyleSheet("image: url(:/newPrefix/D:/Draw Io/drive-download-20240321T065022Z-001/unmul.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(110, 120, 91, 61))
        self.label_8.setStyleSheet("image: url(:/newPrefix/D:/Draw Io/drive-download-20240321T065022Z-001/person-icon-1682.png)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.Nama_lengkap = QtWidgets.QLabel(self.frame)
        self.Nama_lengkap.setGeometry(QtCore.QRect(240, 110, 111, 41))
        self.Nama_lengkap.setObjectName("Nama_lengkap")
        self.Tempat_dan_tanggal_lahir = QtWidgets.QLabel(self.frame)
        self.Tempat_dan_tanggal_lahir.setGeometry(QtCore.QRect(240, 190, 211, 21))
        self.Tempat_dan_tanggal_lahir.setObjectName("Tempat_dan_tanggal_lahir")
        self.Email = QtWidgets.QLabel(self.frame)
        self.Email.setGeometry(QtCore.QRect(240, 260, 81, 21))
        self.Email.setObjectName("Email")
        self.No_hp = QtWidgets.QLabel(self.frame)
        self.No_hp.setGeometry(QtCore.QRect(240, 450, 51, 21))
        self.No_hp.setObjectName("No_hp")
        self.Asal_sekolah = QtWidgets.QLabel(self.frame)
        self.Asal_sekolah.setGeometry(QtCore.QRect(240, 330, 111, 21))
        self.Asal_sekolah.setObjectName("Asal_sekolah")
        self.Alamat = QtWidgets.QLabel(self.frame)
        self.Alamat.setGeometry(QtCore.QRect(240, 390, 61, 21))
        self.Alamat.setObjectName("Alamat")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(290, 10, 311, 61))
        self.label_14.setObjectName("label_14")
        self.Daftar = QtWidgets.QPushButton(self.frame)
        self.Daftar.setGeometry(QtCore.QRect(540, 350, 101, 41))
        self.Daftar.setStyleSheet("border-radius:10px;\n"
"background-color: #005500;\n"
"color: #ffffff;\n"
"font-size:20px;\n"
"font-weight- 200;")
        self.Daftar.setObjectName("Daftar")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(520, 100, 341, 231))
        self.label_7.setStyleSheet("image: url(:/newPrefix/D:/Draw Io/drive-download-20240321T065022Z-001/san-francisco-cityscape-street-city-wallpaper-9049be039bc1edca8080e73e98c40b6d.jpg)")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(240, 150, 271, 31))
        self.plainTextEdit.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(240, 220, 271, 31))
        self.plainTextEdit_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(240, 290, 271, 31))
        self.plainTextEdit_3.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(240, 350, 271, 31))
        self.plainTextEdit_4.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(240, 410, 271, 31))
        self.plainTextEdit_5.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(240, 480, 271, 31))
        self.plainTextEdit_6.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.ubah = QtWidgets.QPushButton(self.frame)
        self.ubah.setGeometry(QtCore.QRect(670, 350, 101, 41))
        self.ubah.setStyleSheet("border-radius:10px;\n"
"background-color: #005500;\n"
"color: #ffffff;\n"
"font-size:20px;\n"
"font-weight- 200;")
        self.ubah.setObjectName("ubah")
        self.hapus = QtWidgets.QPushButton(self.frame)
        self.hapus.setGeometry(QtCore.QRect(670, 400, 101, 41))
        self.hapus.setStyleSheet("border-radius:10px;\n"
"background-color: #005500;\n"
"color: #ffffff;\n"
"font-size:20px;\n"
"font-weight- 200;")
        self.hapus.setObjectName("hapus")
        self.bersihkan = QtWidgets.QPushButton(self.frame)
        self.bersihkan.setGeometry(QtCore.QRect(540, 400, 101, 41))
        self.bersihkan.setStyleSheet("border-radius:10px;\n"
"background-color: #005500;\n"
"color: #ffffff;\n"
"font-size:20px;\n"
"font-weight- 200;")
        self.bersihkan.setObjectName("bersihkan")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">Developed By : Yasser Naufal Attalla</span></p></body></html>"))
        self.Nama_lengkap.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">NAMA LENGKAP</span></p></body></html>"))
        self.Tempat_dan_tanggal_lahir.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">TEMPAT &amp; TANGGAL LAHIR</span></p></body></html>"))
        self.Email.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">EMAIL</span></p></body></html>"))
        self.No_hp.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">NO. HP</span></p></body></html>"))
        self.Asal_sekolah.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">ASAL SEKOLAH</span></p></body></html>"))
        self.Alamat.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:11pt;\">ALAMAT</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Pendaftaran Mahasiswa</span></p></body></html>"))
        self.Daftar.setText(_translate("Form", "DAFTAR"))
        self.ubah.setText(_translate("Form", "UPDATE"))
        self.hapus.setText(_translate("Form", "DELETE"))
        self.bersihkan.setText(_translate("Form", "CLEAR"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
